Full project
z4cope/Hackathon pull request #2
Opened 2022-10-19 15:16 UTC by z4cope

- Started with mobile view.
- Added styles using SASS and split every page and components styles.
- Added the Navbar as a component so it's reused on the other page.
- Added markup and styles for the home page.
- Added the menu scripts so it opens and closes on the mobile.
- Adjusted the home page to be responsive.
- Added the about page markup and styles.
- Linked everything together.
- Added page transition on navigating from one page to another.

2022-10-19 16:33 UTC, jerryowusu requested changes
Hi @z4cope :wave: 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


![so close](https://user-images.githubusercontent.com/65233860/196750951-21276518-c452-439e-87b3-bc859842caaa.gif)


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-10-19 16:33 UTC, jerryowusu commented on README.md
> +
Kindly make sure that the acknowledgement section gives appropriate credit to `Cindy Shim` the `author of the original design`, as required by the `Creative Commons License`.

2022-10-19 16:33 UTC, jerryowusu commented on README.md
> +
The live version here is not working as expected. Kindly make sure that your project is properly hosted/deployed on GitHub Pages. Also kindly ensure that all pages, links, and images work as expected. :+1:

2022-10-19 16:33 UTC, jerryowusu commented on index.html
> +          <li>English</li>
Your design is missing the logout button which is an important feature that cannot be overlooked. Please it in order to conform to the design. :pray: 

Your design             |  The actual design
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-19 15-49-48](https://user-images.githubusercontent.com/65233860/196741395-c99d9d6e-b8fa-402d-8be0-be234c7ba3f4.png)  |  ![Screenshot from 2022-10-19 15-49-03](https://user-images.githubusercontent.com/65233860/196741510-d04ef580-6823-4b50-a612-52c6eca91700.png)

2022-10-19 16:33 UTC, jerryowusu commented on index.html
> +          <li>English</li>
Kindly wrap this in a nav tag just as you did for the nav menu below since they are also navigation and is good for SEO purposes and accessibily readers.

2022-10-19 16:33 UTC, jerryowusu commented on index.html
> +      </nav>
The pages should look almost identical to the original design as much as possible :+1: . Kindly check and make sure that the call to action link do not overlap and extends to the right as shown below. 

Your design             |  The actual design
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-19 16-19-34](https://user-images.githubusercontent.com/65233860/196749026-3973a1c0-3e00-46bd-8936-a0d907416763.png)  |  ![Screenshot from 2022-10-19 16-21-10](https://user-images.githubusercontent.com/65233860/196749081-919a5299-ba9f-4449-aad0-011119fb1455.png)

2022-10-19 16:33 UTC, jerryowusu commented on index.html
> +        </div>
Kindly check and ensure that the speakers section conform to the design. The height of the text and title part are currently longer than the picture part which is not suppose to be so. Please rectify this anomaly :pray: 

Your design             |  The actual design
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-19 16-19-03](https://user-images.githubusercontent.com/65233860/196749773-0df1f19a-ca86-464d-b028-f7dc947cd8dc.png)  |  ![Screenshot from 2022-10-19 16-21-20](https://user-images.githubusercontent.com/65233860/196749813-90381dee-cad4-4724-b109-d666e319eecf.png)

2022-10-19 16:33 UTC, jerryowusu commented on index.html
> +        </button>
[OPTIONAL] In conformity to standard best practices, the more button should change to less when all the speakers are displayed. 

![Screenshot from 2022-10-19 16-18-48](https://user-images.githubusercontent.com/65233860/196750602-eb51807d-db7e-4795-a77e-3faff0d6eeab.png)

2022-10-20 14:59 UTC, ichala approved these changes
Hi @z4cope   ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️  


 Good job implementing the required changes :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :
_ N/A
**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 16:19 UTC, merged